# Travis config for EMA workbench
language: python
sudo: false

python:
  - 2.7
  - 3.5


install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c conda conda-env
  - conda update -q conda --no-deps
  - conda info -a # Useful for debugging any issues with conda
  - conda install mock # Replace dep1 dep2 ... with your dependencies
  - pip install coveralls
  - pip install jpype1

# jpype installation code to be added

before_install:
  - "sh -e /etc/init.d/xvfb start"

script:
  - nosetests --with-coverage --verbose --cover-package=pyNetLogo


# coverage needs to be added
after_success:
  - coveralls

#notifications:
#email: false